server:
  port: 9090
  tomcat:
    threads:
      max: 100
spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  application:
    name: webflux-test
  datasource:
#    driver-class-name: org.hibernate.dialect.H2Dialect
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    h2:
      console:
        enabled: true
        path: /h2-db
  jpa:
    database: H2
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  r2dbc:
    url: r2dbc:h2:mem:///testdb2
    name: sa
    pool:
      initial-size: 100
      max-size: 500
      max-idle-time: 30m
      validation-query: SELECT 1

datasource:
  article:
    url: jdbc:h2:mem:testdb
    username: sa
  user:
    url: r2dbc:h2:mem:///testdb2
    username: sa
