server:
  port: 9090
  tomcat:
    threads:
      max: 100
spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  application:
    name: webflux-test
  datasource:
    url: jdbc:mysql://localhost:3306/storedb?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1
  jpa:
    database: H2
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  r2dbc:
    url: r2dbc:mysql://localhost:3306/storedb
    username: root
    password: password
    pool:
      initial-size: 100
      max-size: 500
      max-idle-time: 30m
      validation-query: SELECT 1
