server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/storedb?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1
  jpa:
    show-sql: true
    generate-ddl: false
    database: mysql
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        format_sql: true
#  r2dbc:
#    url: r2dbc:pool:mysql://127.0.0.1:3306/storedb
#    username: root
#    password: password
#    pool:
#      initial-size: 100
#      max-size: 500
#      max-idle-time: 30m
#      validation-query: SELECT 1

logging:
  level:
    jdbc.sqlonly: DEBUG
    org.springframework.web: DEBUG
    com.zaxxer.hikari.HikariDataSource: ERROR
